### ISSUE TITLE
Regression with WhatsApp

### ISSUE THREAD

**Issue by kytwb** [kytwb/ferdi#19]
See https://github.com/kytwb/ferdi/pull/17#issuecomment-528880912:

> It looks like v5.3.0 has some difficulties with the WhatsApp recipe. The recipe solves the "WhatsApp works with Google Chrome 49+" by removing the "Franz" from the user agent ([meetfranz/recipe-whatsapp:index.js@9797764#L3](https://github.com/meetfranz/recipe-whatsapp/blob/979776457c92ccc915a0084bb190129a7be37aa0/index.js#L3)), but this PR replaced Franz with Ferdi

**Comment by AGCaesar** [comment]
I changed all "Fanz" occurrences in ~.config/Ferdi/recipes/whatsapp/index.js to "Ferdi" and now it works great :) 
Thanks for the 5.3 release!

**Comment by ZeroCool940711** [comment]
As an extra for those of us using Ferdi on Windows that folder mentioned before by AGCaesar can be located quickly by pressing `Win+R` and then typing `%APPDATA%/Ferdi/recipes/whatsapp`, that will take you directly to that folder.

**Comment by vantezzen** [comment]
This bug should be fixed quite easily, I am currently taking a look at what the best fix would be.

**Comment by vantezzen** [comment]
@kytwb The problem should be fixed by 1b18a7b, can you take a look?

**Comment by kytwb** [comment]
Will ship when closing https://github.com/kytwb/ferdi/issues/23.

**Comment by PandaWhisperer** [comment]
> I changed all "Fanz" occurrences in ~.config/Ferdi/recipes/whatsapp/index.js to "Ferdi" and now it works great :)

This worked for me, or at least it did once I figured out that on MacOS, this file is located at `~/Library/Application Support/Ferdi/recipes/whatsapp/index.js`.

**Comment by kytwb** [comment]
@PandaWhisperer do you still need this manual fix with the latest version?

**Comment by PandaWhisperer** [comment]
@kytwb I am on 5.3.0, installed about a week ago via Homebrew. As far as I can tell, that is the latest version (in-app update checks confirms this).

**Comment by vantezzen** [comment]
@PandaWhisperer The newest version is 5.3.3, this bug should be fixed in 5.3.1+ (although you sometimes need to reload WhatsApp using CMD+R to work).
Can you try updating the cask via Homebrew or manually upgrading Ferdi?

**Comment by PandaWhisperer** [comment]
@vantezzen I tried both, but neither the in-app update checker or `brew cask outdated` is reporting any available updates to install.

Also, since I just manually fixed it, I don't suppose installing newer version of Ferdi would overwrite those changes? I assume the config directory is only created once, when Ferdi is started for the first time.

**Comment by vantezzen** [comment]
Ferdi won't overwrite the WhatsApp recipe but v5.3.1 added the fix [directly to Ferdi's code](https://github.com/getferdi/ferdi/commit/1b18a7bca03de32913bc72493ac60017f89c9237#diff-c3386349bcde3a47628bff8e89fa160cR170) and uses is across all services.

**Comment by PandaWhisperer** [comment]
@vantezzen gotcha. So while Ferdi still doesn't show up when I run `brew cask outdated`, I do seem to be able get the newest version by running `brew cask upgrade ferdi`. 

It's downloading 5.3.3 right now. Perhaps `brew cask outdated` is broken, or casks just work differently?

**Comment by vantezzen** [comment]
> `brew cask outdated` shows a list of outdated casks [**that do not auto-update themselves**](https://github.com/Homebrew/homebrew-cask/issues/37294#issuecomment-319537156). Ferdi however, [does auto-update](https://github.com/Homebrew/homebrew-cask/blob/ea3b252dee9a46de14d751dba96a8f4e24bb34dc/Casks/ferdi.rb#L10) and thus doesn't get shown.
You'll have to run `brew cask outdated --greedy` in order to see if Ferdi is outdated.

https://github.com/getferdi/ferdi/issues/61#issuecomment-533778359

**Comment by SMile61** [comment]
I had the problem today. Replacing Franz occurences by Ferdi in the recipe is still working.
Thanks for the solution

**Comment by StephanBe** [comment]
I also had the same problem with the WhatsApp service today, advertising Chrome 60+. A simple Ferdi reload with Ctrl+Shift+R solved the issue for me already.
